default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: list_product_development

test:
  <<: *default
  database: list_product_test

production:
  <<: *default
  database: list_product_production
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  password: <%= ENV['LIST_PRODUCT_DATABASE_PASSWORD'] %>
